services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    hostname: otel-collector
    restart: always
    environment:
      - HONEYCOMB_API_KEY=<API_KEY>
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./collector_configs/otelcol-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    networks:
      - honeycomb

  loadgen:
    image: ghcr.io/honeycombio/loadgen/loadgen
    environment:
      - HONEYCOMB_API_KEY=<API_KEY>
    volumes:
      - ./loadgen_configs/loadgen_config.yaml:/etc/loadgen/config.yaml
    command:
      ["--config=/etc/loadgen/config.yaml"]
    networks:
      - honeycomb

networks:
  honeycomb:
    driver: bridge


