exporters:
  otlp:
    endpoint: refinery:9090
    tls:
      insecure: true
    headers:
      x-honeycomb-team: "${HONEYCOMB_API_KEY}"
  debug:
    verbosity: detailed

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 800
    spike_limit_mib: 250
  batch: {}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
